- name: Install Kubernetes Dependencies
  apt:
    name: [ 'conntrack', 'ipset', 'socat' ]
    state: latest
    update_cache: yes
  tags:
    - binaries


- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/lib/kubernetes
    - /var/lib/kubelet
  tags:
    - config
    - copy-tls


- name: Copy TLS Certificate (ca.pem)
  copy:
    src: "lib/group/{{ env_context }}/ca.pem"
    dest: /var/lib/kubernetes/ca.pem
  tags:
    - copy-tls


- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present


- name: Load br_netfilter module on startup
  copy:
    dest: /etc/modules-load.d/k8s-worker.conf
    content: br_netfilter

