- hosts: etcd
  become: true
  roles:
    - etcd

- hosts: masters
  become: true
  roles:
    - k8s-master
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- hosts: workers
  become: true
  roles:
    - k8s-worker
    - kube-proxy
    - kubelet

# This is a workaround to avoid CNI not getting initialized
- hosts: workers
  name: Restart Worker
  ansible.builtin.reboot:
