- name: Install crictl
  unarchive:
    src: https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ cri_version }}/crictl-v{{ cri_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin/
    owner: root
    group: root
    remote_src: yes
  tags:
    - binaries

