- name: Install runc
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64
    dest: /usr/local/bin/runc
    mode: 0755
    owner: root
    group: root
  tags:
    - binaries

